name: generate breakout svg
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate-breakout-game-from-github-contribution-graph
        uses: cyprieng/github-breakout@v1.0.0